package secrets

import (
	"bufio"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/nicolaeser/RakazoManager/internal/fsutil"
	"github.com/nicolaeser/RakazoManager/internal/stack"
)

const (
	PostgresPassword = "POSTGRES_PASSWORD"
	DatabaseURL      = "DATABASE_URL"
	BetterAuthSecret = "BETTER_AUTH_SECRET"
	EncryptionKey    = "ENCRYPTION_KEY"
	SupervisorToken  = "SANDBOX_SUPERVISOR_TOKEN"
	OpenRouterAPIKey = "OPENROUTER_API_KEY"
	ComposioAPIKey   = "COMPOSIO_API_KEY"
	postgresUser     = "rakazo"
	postgresDatabase = "rakazo"
)

type Store struct {
	Paths stack.Paths
}

type Values map[string]string

func (s Store) LoadOrCreate() (Values, bool, error) {
	values, err := s.Load()
	created := false
	if err != nil {
		if !os.IsNotExist(unwrapPathError(err)) {
			return nil, false, err
		}
		values = Values{}
		created = true
	}
	changed, err := ensureRequired(values)
	if err != nil {
		return nil, false, err
	}
	if created || changed {
		if err := s.Save(values); err != nil {
			return nil, false, err
		}
	}
	return values, created, nil
}

func (s Store) Load() (Values, error) {
	file, err := os.Open(s.Paths.Secrets)
	if err != nil {
		return nil, fmt.Errorf("open instance secrets: %w", err)
	}
	defer file.Close()

	values := Values{}
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, value, found := strings.Cut(line, "=")
		if !found || strings.TrimSpace(key) == "" {
			return nil, fmt.Errorf("invalid secrets line: %q", line)
		}
		values[strings.TrimSpace(key)] = value
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("read instance secrets: %w", err)
	}
	return values, nil
}

func (s Store) Save(values Values) error {
	if err := refreshDatabaseURL(values); err != nil {
		return err
	}
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	var content strings.Builder
	content.WriteString("# Generated by Rakazo Manager. Keep this file private.\n")
	for _, key := range keys {
		value := values[key]
		if strings.ContainsAny(key+value, "\r\n\x00") || strings.Contains(key, "=") {
			return fmt.Errorf("secret %s is not a single-line env value", key)
		}
		fmt.Fprintf(&content, "%s=%s\n", key, value)
	}
	if err := fsutil.AtomicWriteFile(s.Paths.Secrets, []byte(content.String()), 0o600); err != nil {
		return fmt.Errorf("save instance secrets: %w", err)
	}
	return nil
}

func (s Store) SetOptional(values Values, key, value string) error {
	switch key {
	case OpenRouterAPIKey, ComposioAPIKey:
	default:
		return fmt.Errorf("unsupported optional secret %s", key)
	}
	if strings.ContainsAny(value, "\r\n\x00") {
		return fmt.Errorf("%s must be a single line without null characters", key)
	}
	values[key] = strings.TrimSpace(value)
	return s.Save(values)
}

func SensitiveValues(values Values) []string {
	var out []string
	for _, key := range []string{
		PostgresPassword,
		DatabaseURL,
		BetterAuthSecret,
		EncryptionKey,
		SupervisorToken,
		OpenRouterAPIKey,
		ComposioAPIKey,
	} {
		if values[key] != "" {
			out = append(out, values[key])
		}
	}
	return out
}

func ensureRequired(values Values) (bool, error) {
	changed := false
	if values[PostgresPassword] == "" {
		password, err := randomHex(16)
		if err != nil {
			return false, err
		}
		values[PostgresPassword] = password
		changed = true
	}
	if values[BetterAuthSecret] == "" {
		secret, err := randomHex(32)
		if err != nil {
			return false, err
		}
		values[BetterAuthSecret] = secret
		changed = true
	}
	if values[EncryptionKey] == "" {
		key, err := randomHex(32)
		if err != nil {
			return false, err
		}
		values[EncryptionKey] = key
		changed = true
	}
	if values[SupervisorToken] == "" || values[SupervisorToken] == values[BetterAuthSecret] {
		token, err := randomHex(32)
		if err != nil {
			return false, err
		}
		for token == values[BetterAuthSecret] {
			token, err = randomHex(32)
			if err != nil {
				return false, err
			}
		}
		values[SupervisorToken] = token
		changed = true
	}
	beforeURL := values[DatabaseURL]
	if err := refreshDatabaseURL(values); err != nil {
		return false, err
	}
	if values[DatabaseURL] != beforeURL {
		changed = true
	}
	return changed, nil
}

func refreshDatabaseURL(values Values) error {
	password := values[PostgresPassword]
	if password == "" {
		return fmt.Errorf("POSTGRES_PASSWORD is required")
	}
	values[DatabaseURL] = fmt.Sprintf("postgres://%s:%s@postgres:5432/%s", postgresUser, password, postgresDatabase)
	return nil
}

func randomHex(bytes int) (string, error) {
	buffer := make([]byte, bytes)
	if _, err := rand.Read(buffer); err != nil {
		return "", fmt.Errorf("generate random credential: %w", err)
	}
	return hex.EncodeToString(buffer), nil
}

func unwrapPathError(err error) error {
	for err != nil {
		if pathError, ok := err.(*os.PathError); ok {
			return pathError.Err
		}
		unwrapper, ok := err.(interface{ Unwrap() error })
		if !ok {
			return err
		}
		err = unwrapper.Unwrap()
	}
	return nil
}
